drop table if exists performance CASCADE;
create table performance(c1 integer);
insert into performance values(1);
insert into performance values(2);
insert into performance values(3);
insert into performance values(4);
insert into performance values(5);
insert into performance values(6);
insert into performance values(7);
insert into performance values(8);
insert into performance values(9);
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance;
insert into performance select * from performance LIMIT 10000000;
insert into performance select * from performance LIMIT 10000000;
insert into performance select * from performance LIMIT 10000000;
insert into performance select * from performance LIMIT 10000000;
insert into performance select * from performance LIMIT 1457280;
select count(*) from performance;
