import typing
import pytest  # type: ignore
import redshift_connector
from enum import IntEnum
from unittest.mock import Mock, PropertyMock, patch


# Define constants
# Used when certain column values are dynamically generated by the server and can't be validated
SKIP_RESULT_VALIDATION: str = "SKIP"

# SQL command to enable case-sensitive identifiers in Redshift
ENABLE_CASE_SENSITIVE_IDENTIFIER_SQL: str = "SET enable_case_sensitive_identifier TO true;"


class ProcedureType(IntEnum):
    RESULT_UNKNOWN = 0
    NO_RESULT = 1
    RETURNS_RESULT = 2


class ProcedureColumnType(IntEnum):
    UNKNOWN = 0
    IN = 1
    IN_OUT = 2
    OUT = 3
    RETURN = 4
    RESULT = 5


class FunctionType(IntEnum):
    UNKNOWN = 0
    NOTABLE = 1
    RETURNS_TABLE = 2


class FunctionColumnType(IntEnum):
    UNKNOWN = 0
    IN = 1
    IN_OUT = 2
    OUT = 3
    RETURN = 4
    RESULT = 5


def get_connection_properties(
        db_kwargs: typing.Dict[str, typing.Union[str, bool, int]],
        current_catalog: str,
        is_single_database_metadata: bool
) -> typing.Dict[str, typing.Union[str, bool, int]]:
    """
    Get database connection properties based on metadata settings.

    Args:
        db_kwargs: Dictionary containing database connection parameters
        current_catalog: Name of the current database/catalog
        is_single_database_metadata: Flag to determine if metadata is for single database

    Returns:
        Dictionary containing modified connection properties
    """
    cur_db_kwargs: typing.Dict[str, typing.Union[str, bool, int]] = db_kwargs.copy()
    if is_single_database_metadata:
        cur_db_kwargs["database_metadata_current_db_only"] = True
        cur_db_kwargs["database"] = current_catalog
    else:
        cur_db_kwargs["database_metadata_current_db_only"] = False
    return cur_db_kwargs

def setup_metadata_test_env(
        db_kwargs: typing.Dict[str, typing.Union[str, bool, int]],
        catalog_name: str,
        setup_statements: typing.Tuple[str, ...],
        require_quoted: bool = False,
        is_case_sensitive: bool = False,
        catalog_sql_name: str = ""
) -> None:
    """
    Sets up the test environment by creating a new database and executing setup statements.

    Args:
        db_kwargs: Database connection parameters
        catalog_name: Name of the database/catalog to create
        setup_statements: List of SQL statements to execute for setup
        require_quoted: Whether to add quotes around the name
        is_case_sensitive: Whether to enable case-sensitive
        catalog_sql_name: catalog name used in SQL query (including escaped quoting)
    """
    # Create a copy of connection parameters to avoid modifying the original
    test_db_kwargs = dict(db_kwargs)

    # First connection: Create the test database
    with redshift_connector.connect(**test_db_kwargs) as con:
        con.paramstyle = "format"
        con.autocommit = True
        with con.cursor() as cursor:
            # Clean up test database if exists
            try:
                if require_quoted:
                    if is_case_sensitive:
                        cursor.execute(ENABLE_CASE_SENSITIVE_IDENTIFIER_SQL)
                    cursor.execute(f'drop database "{catalog_sql_name}"')
                else:
                    cursor.execute(f'drop database {catalog_name}')
            except redshift_connector.ProgrammingError:
                pass # Ignore error if database doesn't exist

            # Create test database
            if require_quoted:
                if is_case_sensitive:
                    cursor.execute(ENABLE_CASE_SENSITIVE_IDENTIFIER_SQL)
                cursor.execute(f'create database "{catalog_sql_name}"')
            else:
                cursor.execute(f'create database {catalog_name}')

    # Second connection: Execute setup statements in the new database
    test_db_kwargs["database"] = catalog_name
    with redshift_connector.connect(**test_db_kwargs) as con:
        with con.cursor() as cursor:
            if is_case_sensitive:
                cursor.execute(ENABLE_CASE_SENSITIVE_IDENTIFIER_SQL)
            for stmt in setup_statements:
                cursor.execute(stmt)
            con.commit()

def teardown_metadata_test_env(
        db_kwargs: typing.Dict[str, typing.Union[str, bool, int]],
        catalog_name: str,
        require_quoted: bool = False,
        is_case_sensitive: bool = False
) -> None:
    """
    Tears down the test environment by dropping the test database.

    Args:
        db_kwargs: Database connection parameters
        catalog_name: Name of the database/catalog to drop
        require_quoted: Whether to enable case-sensitive
        is_case_sensitive: Whether to add quotes around the name
    """
    try:
        with redshift_connector.connect(**db_kwargs) as con:
            con.autocommit = True
            with con.cursor() as cursor:
                if require_quoted:
                    if is_case_sensitive:
                        cursor.execute(ENABLE_CASE_SENSITIVE_IDENTIFIER_SQL)
                    cursor.execute(f'drop database "{catalog_name}"')
                else:
                    cursor.execute(f'drop database {catalog_name}')
    except redshift_connector.ProgrammingError:
        pass # Ignore error if database doesn't exist

def pattern_matches(str1: str, str2: str) -> bool:
    """
    Checks if strings match based on pattern matching rules.

    Args:
        str1: Pattern string (can contain '%' wildcard)
        str2: String to match against

    Returns:
        bool: True if strings match according to the rules
    """
    return str1 is None or str1 == '' or str1 =='%' or str1 == str2 or ('%' in str1 and str2.startswith('test'))

def exact_matches(str1: str, str2: str) -> bool:
    """
    Checks if strings match exactly (or if str1 is None/empty).

    Args:
        str1: First string to compare
        str2: Second string to compare

    Returns:
        bool: True if strings match exactly
    """
    return str1 is None or str1 == '' or str1 == str2

def run_metadata_test(
        db_kwargs: typing.Dict[str, typing.Union[str, bool, int]],
        current_catalog: str,
        is_single_database_metadata: bool,
        min_show_discovery_version: int,
        method_name: str,
        method_args: typing.Tuple,
        expected_col_name: typing.List[str],
        expected_result: typing.List[typing.Any]
) -> None:
    """
    Runs a metadata API test with the specified parameters.

    Args:
        db_kwargs: Database connection parameters
        current_catalog: Name of the current database/catalog
        is_single_database_metadata: Whether to use single database metadata mode
        min_show_discovery_version: Minimum required show discovery version
        method_name: Name of the metadata method to test
        method_args: Arguments to pass to the method
        expected_col_name: Expected column names in the result
        expected_result: Expected result rows
    """
    col_name_index: int = 0
    cur_db_kwargs = get_connection_properties(db_kwargs, current_catalog, is_single_database_metadata)

    with redshift_connector.connect(**cur_db_kwargs) as conn:
        with conn.cursor() as cursor:
            if cursor.get_show_discovery_version() >= min_show_discovery_version:
                method = getattr(cursor, method_name)
                result: tuple = method(*method_args)

                column = cursor.description
                assert len(expected_col_name) == len(column), (
                    f"Column count mismatch for {method_name}. "
                    f"Expected {len(expected_col_name)}, got {len(column)}"
                )

                for expected_col_name, actual_col_description in zip(expected_col_name, column):
                    assert expected_col_name == actual_col_description[col_name_index], (
                        f"Column name mismatch for {method_name}. "
                        f"Expected '{expected_col_name}', got '{actual_col_description[col_name_index]}'"
                    )

                assert len(result) == len(expected_result), (
                    f"Result count mismatch for {method_name}. "
                    f"Expected {len(expected_result)} rows, got {len(result)} rows. "
                    f"Returned result:\n" +
                    "\n".join([str(row) for row in result])
                )

                # Compare each row
                for actual_row, expected_row_info in zip(result, expected_result):
                    # Get all fields from the dataclass
                    expected_row = [getattr(expected_row_info, field) for field in expected_row_info.__dataclass_fields__]
                    for col_index in range(len(expected_row)):
                        if expected_row[col_index] == SKIP_RESULT_VALIDATION:
                            continue
                        assert actual_row[col_index] == expected_row[col_index], (
                            f"Value mismatch in {method_name}, column {col_index + 1}. "
                            f"Expected '{expected_row[col_index]}', got '{actual_row[col_index]}'. "
                            f"Args: {method_args}. "
                            f"Entire row: {actual_row}"
                        )
            else:
                with pytest.raises(redshift_connector.InterfaceError,
                                    match="Current cluster doesn't support required SHOW command"):
                    method = getattr(cursor, method_name)
                    method(*method_args)
